[en]
  languageName = "English"
  weight = 1

  [en.params]
    displayName = "EN"
    isoCode = "en"
    rtl = false
    dateFormat = "2 January 2006"
    
    headline = "Welcome to DominikZone"
    description = "Linux Mint | 42Warsaw | ComfyUI & AI & Gaming"
    
    [en.params.author]
      name = "Dominik"
      image = "me.webp" 
      headline = "Tech Enthusiast & Developer"
      bio = "A blog about switching from Windows to Linux, learning programming, and generating schedules in AI."
      
      links = [
        { github = "https://github.com/dominikzone" },
        { youtube = "https://www.youtube.com/@dominikzone" }
      ]