colorScheme = "blowfish"
defaultAppearance = "dark"

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 5

[article]
  showDate = true
  showTags = true
  showReadingTime = true
  showComments = true

[search]
  enable = true
  type = "fuse"
  showStandardSearch = true

[comments]
  system = "giscus"

[comments.giscus]
  repo = "dominikzone/dominikzone-blog"
  repoId = "R_kgDORVweAg"
  category = "Announcements"
  categoryId = "DIC_kwDORVweAs4C28qI"
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "top"
  theme = "preferred_color_scheme"
  lang = "en"

[analytics]
  provider = "umami"

[analytics.umami]
  websiteId = "7f514288-e30b-4add-82c4-71b082ceffe8"
  url = "https://cloud.umami.is/script.js"